### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by miekg** [coredns/new.coredns.io#1]
# TODO:

* [x] <strike>artwork</strike> - will come later
* [x] fix homepage text
* [x] colors - pick color from CoreDNS pallet 
* [x] remove the word 'Kube' from everywhere
* [x] nice page footer
* [x] footer does not work on mobile
* [x] external middleware setup, i.e. how to link to what?
* [x] automatically link to the latest release notes for CoreDNS from the homepage
* [x] more text in the middleware page; link to some docs?
* [x] fix archetypes

**Comment by miekg** [comment]
@johnbelamaric @chrisohaver @pmoroney @varyoo 

please let me know what you want changed or see improved. New site design is visible on new.coredns.io
(if you want to hack locally you'll need hugo and this repo obviously)

**Comment by miekg** [comment]
Ok, pushed to https://new.coredns.io .

I kinda like it already. Awaiting your feedback before pushing it live.
(also need to write some more docs)

**Comment by pmoroney** [comment]
The quick start link doesn't seem to go anywhere on my phone. But I like
the look!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/new.coredns.io] todo (..." ]
>The quick start link doesn't seem to go anywhere on my phone. But I like
>the look!

Thanks! Good to hear - yes, I'll still need to write a few docs to fill in the 
blanks (files issues for those).

**Comment by chrisohaver** [comment]
Look and feel is nice and clean.  Slightly rounder corners on the navigation buttons may fit better with the CoreDNS logo (echoing the "middleware chain links" in the logo).

I think we only need one of "How to Write Middleware" or "How to Add Middleware" links in the middleware section... It was unclear to me what the distinction was between the two until I read the last sentence on the latter ... "This is an updated version of the previous blog about writing CoreDNS middleware."  ... or perhaps consolidate the two.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/new.coredns.io] todo (..." ]
>Look and feel is nice and clean.  Slightly rounder corners on the navigation buttons may fit better with the CoreDNS logo (echoing the "middleware chain links" in the logo).

yes, that sounds a good plan.

>I think we only need one of "How to Write Middleware" or "How to Add Middleware" links in the middleware section... It was unclear to me what the distinction was between the two until I read the last sentence on the latter ... "This is an updated version of the previous blog about writing CoreDNS middleware."  ... or perhaps consolidate the two.

Ack. I rushed this a bit, so I suspected there might be room for improvement 
here.

(I'll won't change this now. First want to push it live)

/Miek

--
Miek Gieben
